/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#414755",
        "surface-container-low": "#181c23",
        "on-background": "#e0e2ed",
        "on-tertiary": "#472a00",
        "on-secondary": "#003824",
        "on-error": "#690005",
        "on-secondary-fixed": "#002113",
        "on-surface-variant": "#c1c6d7",
        "on-error-container": "#ffdad6",
        primary: "#adc6ff",
        "inverse-on-surface": "#2d3039",
        "primary-fixed-dim": "#adc6ff",
        surface: "#10131b",
        "surface-tint": "#adc6ff",
        "on-tertiary-fixed-variant": "#653e00",
        background: "#10131b",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-bright": "#363942",
        "inverse-surface": "#e0e2ed",
        "surface-container-lowest": "#0b0e16",
        "tertiary-container": "#ca8100",
        "primary-fixed": "#d8e2ff",
        "on-primary-container": "#00285c",
        secondary: "#4edea3",
        "tertiary-fixed": "#ffddb8",
        "primary-container": "#4b8eff",
        "surface-variant": "#31353d",
        outline: "#8b90a0",
        "surface-container-high": "#272a32",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#31353d",
        error: "#ffb4ab",
        "on-secondary-container": "#00311f",
        "error-container": "#93000a",
        "on-surface": "#e0e2ed",
        "on-primary-fixed-variant": "#004493",
        "on-secondary-fixed-variant": "#005236",
        "on-primary": "#002e69",
        "on-tertiary-container": "#3e2400",
        "on-primary-fixed": "#001a41",
        "secondary-container": "#00a572",
        "surface-dim": "#10131b",
        "inverse-primary": "#005bc1",
        "secondary-fixed-dim": "#4edea3",
        tertiary: "#ffb95f",
        "secondary-fixed": "#6ffbbe",
        "surface-container": "#1c2028",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "0.5rem",
        xs: "0.25rem",
        xl: "2rem",
        lg: "1.5rem",
        md: "1rem",
        gutter: "1rem",
        base: "4px",
        "container-margin": "2rem",
      },
      fontFamily: {
        "body-base": ["Hanken Grotesk", "sans-serif"],
        "code-snippet": ["JetBrains Mono", "monospace"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "status-label": ["JetBrains Mono", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-base": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "code-snippet": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "status-label": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
